# Generated by Django 5.0.4 on 2024-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Complete')], default=1),
        ),
    ]
