# Generated by Django 5.0.4 on 2024-05-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tododata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Complete')], default=0),
        ),
    ]
